PolicyApp/PolicyApp/Models/BusinessObjects.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PolicyApp.Models
{
    public class BusinessObjects
    {
    }

    public class Policy {
        public string policyno { get; set; }
        public string Policytype { get; set; }
        public string PersonName { get; set; }
        public string Address { get; set; }
        public string Risktype { get; set; }
        public string city { get; set; }
        

    }
}

PolicyApp/PolicyApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PolicyApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PolicyApp/PolicyApp/Controllers/PolicytController.cs
using PolicyApp.Apicall;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PolicyApp.Models;
using Newtonsoft.Json;

namespace PolicyApp.Controllers
{
    public class PolicytController : Controller
    {
        // GET: Policyt


        Service consume = new Service();
        [HttpGet]       
        public ActionResult Index()
        {
            
            ViewBag.policylist = plist(); 
           
            return View();
        }
        [HttpPost]      
        public ActionResult Index(Policy obj)
        {
           
            try
            {
          
                ViewBag.policylist = plist();

                var response = consume.savepolicy(obj);              
                
                List<Policy> Products = JsonConvert.DeserializeObject<List<Policy>>(response.Content);
                ViewBag.returndata= Products;
            }
            catch (Exception ex)
            {
                Response.Write("<script> alert('Sorry, Something Went Wrong...!');window.location ='/Policyt/Index';</script>");
            }

            return View();
        }

        public List<SelectListItem> plist() {
            List<SelectListItem> policylist = new List<SelectListItem>()
            {

                new SelectListItem { Text = "Personal Auto", Value = "PA" },
                new SelectListItem { Text = "Home Owners", Value = "HO" },
                new SelectListItem { Text = "Business Owners", Value = "BO" }

            };
            return policylist;

        }
    }
}

PolicyApp/PolicyApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PolicyApp/PolicyApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PolicyApp/PolicyApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PolicyApp/PolicyApp/Views/Policyt/Index.cshtml
@model PolicyApp.Models.Policy
@{
    ViewBag.Title = "Policy general Information | ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="row" style="padding-bottom: 50px; margin-top: 55px;">
    <div class="col-md-6 col-lg-6 col-xs-12 " style="align-items: center;">
        <img src="~/assets/images/policy.jpg" class="sizeimage" />
    </div>
    <div class="col-md-6 col-lg-6 col-xs-12  mobile ">
        <!--Start Contact Form-->
      
        @using (Html.BeginForm("Index", "Policyt", FormMethod.Post))
        {
            <div class="contact-form" style="float: right;">
                <h3 class="letter1">Policy general Information form</h3>
                <p class="letter2">Please fill out below details.</p>


                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group form-element">

                            @*@Html.DropDownList("policylist", (IEnumerable<SelectListItem>)ViewBag.policylist, "Select Policy", new { @id = "policylist", @class = "form-control" })*@

                            @Html.DropDownListFor(m => m.Policytype, (IEnumerable<SelectListItem>)ViewBag.policylist, "Select Policy", new { @id = "policylist", @class = "form-control", @onchange = "Policycontent()" })

                            @*@Html.TextBoxFor(m => m.Policytype, new { placeholder = "Policytype.", @class = "form-control input-field ", @id = "Policytype" })*@
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group form-element">

                            @Html.TextBoxFor(m => m.policyno, new { placeholder = "Policyno.", @class = "form-control input-field ", @id = "policyno", @readonly = true })
                        </div>
                    </div>

                    <!-- Trigger/Open The Modal -->

                    <div id="myModal" class="modal">

                        <!-- Modal content -->
                        <div class="modal-content">
                            <span class="close">&times;</span>
                            @*<p> <input id="policycode" type="text" rows="5" /></p>*@
                            <textarea id="policycode" class="form-control" style="min-width: 100%;resize:none;" readonly></textarea>

                            <textarea id="policycodedate" class="form-control" style="min-width: 100%;resize:none;" readonly></textarea>

                        </div>

                    </div>

                    <div class="col-md-12">
                        <div class="form-group form-element">

                            @Html.TextBoxFor(m => m.PersonName, new { placeholder = "Name.", @class = "form-control input-field ", @id = "PersonName" })
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group form-element">

                            @Html.DropDownList("Risktype", new List<SelectListItem>
  {
      new SelectListItem{ Text="Select Region", Value = "Select Region" },
      new SelectListItem{ Text="Urban", Value = "Urban" },
      new SelectListItem{ Text="Rural", Value = "Rural" },
   },new {@id= "Risktype" , @class = "form-control input-field " })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-element">

                            @Html.TextBoxFor(m => m.city, new { placeholder = "City.", @class = "form-control input-field ", @id = "city" })
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group form-element">

                            @Html.TextBoxFor(m => m.Address, new { placeholder = "Address.", @class = "form-control input-field ", @id = "Address" })
                        </div>
                    </div>

                </div>
                <div class="contact-frm-btn">

                    <input id="btnsubmit" type="submit" value="Submit" onclick="return checkvalidation();" class="mr_btn_fill" />

                </div>


            </div>
        }
        <input id="myBtn" type="button" style="display:none;" value="Open Modal" />
        <!--End Contact Form-->
    </div>
    <div class="col-md-6 col-lg-6 col-xs-12" style="align-items: center">
    </div>
    <div class="col-md-6 col-lg-6 col-xs-12" style="align-items: center">
        @if (ViewBag.returndata != null)
        {
            <h3 class="letter1">Policy Person details</h3>
            <div class="table-responsive  mobile" style="padding-top: 10px;">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>PolicyNo</th>
                            <th>Policy Name</th>
                            <th>Risk Region</th>
                            <th>Name</th>
                            <th>Address</th>
                        </tr>


                        @foreach (var item in (IEnumerable<PolicyApp.Models.Policy>)ViewBag.returndata)
                        {

                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.policyno)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Policytype)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Risktype)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PersonName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.city),  @Html.DisplayFor(modelItem => item.Address)
                            </td>

                            <td>


                        </tr>
                        }
                    </tbody>
                </table>

            </div>
        }

    </div>

</div>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<style>

    .toast-top-center {
        margin: 0 auto;
        left: 50%;
        color: white;
    }

    .tost-class {
        /*background-color: #ff2d55;*/
        background-color: black;
        width: 500px !important;
    }
</style>
<script>
    function failure(message) {
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "progressBar": true,
            "preventDuplicates": false,
            "positionClass": "toast-top-right",
            "showDuration": "400",
            "hideDuration": "1000",
            "timeOut": "2000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["error"](message);

    }
    function success(message) {
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "progressBar": true,
            "preventDuplicates": false,
            "positionClass": "toast-top-right",
            "showDuration": "400",
            "hideDuration": "1000",
            "timeOut": "2000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr["success"](message);

    }
</script>


<script type="text/javascript">
    function checkvalidation() {
        if (document.getElementById("policylist").value == "") {
         
            document.getElementById("policylist").focus();

            failure("select policylist");
            return false;
        }
        else if (document.getElementById("policyno").value == "") {
            document.getElementById("policyno").focus();
            failure("Enter Policy Number");
            return false;
        }

      

        else if (document.getElementById("PersonName").value == "") {
            document.getElementById("PersonName").focus();

          
            failure("Enter Name");
            return false;
        }
        else if (document.getElementById("Risktype").value == "Select Region") {
            document.getElementById("Risktype").focus();

          
            failure("Select your region");
            return false;
        }
        
        else if (document.getElementById("city").value == "") {
            document.getElementById("city").focus();

          
            failure("Enter City");
            return false;
        }
        else if (document.getElementById("Address").value == "") {
            document.getElementById("Address").focus();

            failure("Enter Address");
            return false;
        }
       

        

    }


</script>


<script type="text/javascript">


    function Policycontent() {
        var chars = "0123456789";

        var string_length = 5;

        var code = "";

        for (var i = 0; i < string_length; i++) {
            var rnum = Math.floor(Math.random() * chars.length);

            code += chars.substring(rnum, rnum + 1);
        }

        var txt = document.getElementById('policycode');
        var date = document.getElementById('policycodedate');
        var policycodenu = document.getElementById("policyno");

        if (document.getElementById("policylist").value == "PA") {
            policycodenu.value = "PA" + code;
            txt.value = "Dear applicant you have choosed Personal Auto policy ";
            date.value = "This term effects from Jan 2021 and expires on Jan 2022";
            // alert(txt.value);
        }
        else if (document.getElementById("policylist").value == "HO") {
            policycodenu.value = "HO" + code;
            txt.value = "Dear applicant you have choosed Home Owners";
            date.value = "This term effects from Feb 2021 and expires on Feb 2022";
            // alert(txt.value);
        }
        else if (document.getElementById("policylist").value == "BO") {
            policycodenu.value = "BO" + code;
            txt.value = "Dear applicant you have choosed Business Owners";
            date.value = "This term effects from Mar 2021 and expires on Mar 2022";
            // alert(txt.value);
        }

        //txt.value = document.getElementById("policylist").value;
        var modal = document.getElementById("myModal");
        modal.style.display = "block";


        // alert(code);


    }
</script>

<style>
    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: absolute; /* Stay in place */
        z-index: 1; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content/Box */
    .modal-content {
        background-color: #fefefe;
        margin: 15% auto; /* 15% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }

    /* The Close Button */
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
</style>

<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function () {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>

PolicyApp/PolicyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Jarus</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@

    <title>Jarus</title>
    <!--Favicon-->
   
    <!--Bootstrap Stylesheet-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap.css">
    <!--Font Awesome Stylesheet-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/font-awesome.min.css">
    <!-- flat icon  -->
    <link rel="stylesheet" type="text/css" href="~/assets/fonts/flaticon.css">
    <!--Animate Stylesheet-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/animate.css">
    <!--Main Stylesheet-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <!--Responsive Stylesheet-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/responsive.css">
    <!--Modanizr JS-->
    <script src="~/assets/js/modernizr.custom.js"></script>
    <style>
        @@media screen and (max-width:640px) {
            .sizeimage {
                height: 420px;
                margin-left: -79px;
                position: absolute;
                margin-top: -72px;
                width: 136%;
            }

            .contact-form {
                background: #0000008a;
                color: white;
                margin: 1px;
                /* padding-left: 20px; */
                padding: 10px;
                padding-top: 0px;
            }

            .footletter {
                margin-top: 0px;
            }

            .letter1 {
                font-size: 20px !important;
            }

            .container_login {
                margin-bottom: -135px;
            }

            .letter2 {
                margin-top: -25px !important;
                font-size: 13px !important;
            }

            .letter3 {
                color: white;
                text-anchor: start;
            }


            .contct-form {
                /*align-items: center;
                margin-left: -85px;
                margin-right: 85px;*/
                float: right;
                background: #1a6ab166;
                margin-top: -50px;
            }
            .modal {
                margin-left: 20px !important;
                width: 90% !important;
            }
            .close {
                padding-left: 245px;
                color:red !important;
            }
           
        }

        @@media screen and (min-width:641px) {
            .sizeimage {
                height: 370px;
                margin-left: -47px;
                position: absolute;
            }
        }

        .contact-wrap {
            margin-bottom: 28px;
        }
    </style>

    <style>
        @@media only screen and (max-device-width: 400px) {

            .mobile {
                width: 41%
            }
            
        }
        @@media only screen and (max-device-width: 320px) {

            .mobile {
                width: 34%
            }
           
        }
        @@media only screen and (max-device-width: 575px) {

            .mobile {
                width: 45%
            }
            .footercenter {
                margin-left: -10px;
            }
            
        }
    </style>
</head>

<body class="body-class index_1">
    <!--Start Preloader-->
    @*<div class="site-preloader">
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
    </div>*@
    <!--End Preloader-->
    <!--Start Body Wrap-->
    <div id="body-wrap">
        <!--Start Header-->
        <header id="mainHeader" class="header">
            <!-- Start Navigation -->
            <nav class="navbar navbar-expand-lg navbar-light p-0" style="background-color: #ff2d55">
                <div class="container">
                    <a class="navbar-brand" href="~/Policyt/Index">
                        <img class="logo-dark" src="https://jarustech.com/Content/images/Jarus-Logo.svg" style="height: 70px; width: auto;" alt="Jarus">
                        <img class="logo-light" src="https://jarustech.com/Content/images/Jarus-Logo.svg" style="height: 70px; width: auto;" alt="Jarus">
                    </a>
                 
                </div>
            </nav>
            <!-- End Navigation -->
            <div class="clearfix"></div>
        </header>
        <!--End Header-->
        <!--Start Contact Wrap-->
        <div class="contact-wrap">
            <!--Start Container-->
            <div class="container container_login">
                <!--Contact Map-->
                <!--Start Row-->
              
                 
                @RenderBody()
                    
            
                <!--End Row-->
            </div>
            <!--End Container-->
        </div>
        <!--End Contact Wrap-->
        <!--End Page Content-->
        <!-- google map area start -->
        <!-- google map area end -->
        <!--Start Footer-->
        <footer class="footer ">
            <!--Start Footer Top-->
            <!--End Footer Top-->
            <!--Start Footer Bottom-->
            <div class="footer-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 footletter">
                            <div class="copyright-text mobile footercenter">
                                <p class="color-white">Copyright &copy; @DateTime.Now.Year All Rights Reserved, Powered by </p>
                                <a href="~/Policyt/Index"><span>Jarus</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--End Footer Bottom-->
            <!--Start ClickToTop-->
            <div class="totop">
                <a href="#top"><i class="fa fa-arrow-up"></i></a>
            </div>
            <!--End ClickToTop-->
        </footer>
        <!--End Footer-->
    </div>
    <!--End Body Wrap-->
    <!--jQuery JS-->
    <script src="~/assets/js/jquery.min.js"></script>
    <!--Bootstrap JS-->
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- google map -->
    <script src="~/assets/js/contact-map-active.js"></script>
    <!--Google map JS-->
    <!-- Calender JS-->
 
  


</body>

</html>